Save

diff --git a/modules/daemons/zone b/modules/daemons/zone
--- a/modules/daemons/zone
+++ b/modules/daemons/zone
@@ -64,20 +64,18 @@ __daemon_zone() {
     # Generate zone_up and zone_down
     #
     log_info "[Zone][$name] Generate zone_up."
-    "$SHNETWORKD" ::configureNetwork "$DATA_DIR/$name" up 2> "$RUNTIME_DIR/zone_gen.log" > "$zone_up_file"
-    if [ i'0' != i"$?" ]
-    then
-        log_error "[Zone][$name] Error when composing network configuration for zone." 2>&1 | log_tofile "$log_file"
-        exit 1
-    fi
+    
+    [ { "$SHNETWORKD" ::configureNetwork "$DATA_DIR/$name" up 2> "$RUNTIME_DIR/zone_gen.log" > "$zone_up_file"; } ] || {
+        log_error "[Zone][$name] Error when composing network configuration for zone." 2>&1 | log_tofile "$log_file";
+        exit 1;
+    }
 
     log_info "[Zone][$name] Generate zone_down."
-    "$SHNETWORKD" ::configureNetwork "$DATA_DIR/$name" down 2> "$RUNTIME_DIR/zone_gen.log" > "$zone_down_file"
-    if [ i'0' != i"$?" ]
-    then 
-        log_error "[Zone][$name] Error when composing network configuration for zone." 2>&1 | log_tofile "$log_file"
-        exit 1
-    fi
+    
+    [ { "$SHNETWORKD" ::configureNetwork "$DATA_DIR/$name" down 2> "$RUNTIME_DIR/zone_gen.log" > "$zone_down_file"; } ] || {
+        log_error "[Zone][$name] Error when composing network configuration for zone." 2>&1 | log_tofile "$log_file";
+        exit 1;
+    }
 
     chmod +x "$zone_up_file"
     chmod +x "$zone_down_file"
@@ -90,11 +88,10 @@ __daemon_zone() {
     #
     log_info "[Zone][$name] Execute zone configuration."
     chmod +x "$zone_up_file"
-    if [ ! $(RUNTIME_DIR="$RUNTIME_DIR" "$zone_up_file" 2>&1 | log_tofile "$log_file") ]
-    then
-        log_error "[Zone][$name] Error while activating zone." 2>&1 | log_tofile "$log_file"
-        exit 1
-    fi
+    [ { RUNTIME_DIR="$RUNTIME_DIR" "$zone_up_file" 2>&1 | log_tofile "$log_file"; } ] || {
+        log_error "[Zone][$name] Error while activating zone." 2>&1 | log_tofile "$log_file";
+        exit 1;
+    }
     
     echo "up" > "$stage_file"
 
