Save

diff --git a/modules/daemons/zone b/modules/daemons/zone
--- a/modules/daemons/zone
+++ b/modules/daemons/zone
@@ -65,17 +65,19 @@ __daemon_zone() {
     #
     log_info "[Zone][$name] Generate zone_up."
     
-    [ { "$SHNETWORKD" ::configureNetwork "$DATA_DIR/$name" up 2> "$RUNTIME_DIR/zone_gen.log" > "$zone_up_file"; } ] || {
-        log_error "[Zone][$name] Error when composing network configuration for zone." 2>&1 | log_tofile "$log_file";
-        exit 1;
-    }
+    if [ ! { "$SHNETWORKD" ::configureNetwork "$DATA_DIR/$name" up 2> "$RUNTIME_DIR/zone_gen.log" > "$zone_up_file"; } ]
+    then
+        log_error "[Zone][$name] Error when composing network configuration for zone." 2>&1 | log_tofile "$log_file"
+        exit 1
+    fi
 
     log_info "[Zone][$name] Generate zone_down."
     
-    [ { "$SHNETWORKD" ::configureNetwork "$DATA_DIR/$name" down 2> "$RUNTIME_DIR/zone_gen.log" > "$zone_down_file"; } ] || {
+    if [ ! { "$SHNETWORKD" ::configureNetwork "$DATA_DIR/$name" down 2> "$RUNTIME_DIR/zone_gen.log" > "$zone_down_file"; } ] 
+    then
         log_error "[Zone][$name] Error when composing network configuration for zone." 2>&1 | log_tofile "$log_file";
         exit 1;
-    }
+    fi
 
     chmod +x "$zone_up_file"
     chmod +x "$zone_down_file"
@@ -88,11 +90,12 @@ __daemon_zone() {
     #
     log_info "[Zone][$name] Execute zone configuration."
     chmod +x "$zone_up_file"
-    [ { RUNTIME_DIR="$RUNTIME_DIR" "$zone_up_file" 2>&1 | log_tofile "$log_file"; } ] || {
+    if [ ! { RUNTIME_DIR="$RUNTIME_DIR" "$zone_up_file" 2>&1 | log_tofile "$log_file"; } ]
+    then
         log_error "[Zone][$name] Error while activating zone." 2>&1 | log_tofile "$log_file";
         exit 1;
-    }
-    
+    fi
+
     echo "up" > "$stage_file"
 
     BUS="$manager_bus"
